trigger:
  - master

variables:
  DOTNET_SDK_VERSION: "2.1.401"

pool:
  vmImage: "windows-2019"

steps:
  - task: DotNetCoreInstaller@0
    displayName: "Use .NET Core SDK $(DOTNET_SDK_VERSION)"
    inputs:
      version: "$(DOTNET_SDK_VERSION)"

  - powershell: ./build.ps1
    displayName: "Execute Cake PowerShell Bootstrapper"

  - task: CopyFiles@2
    displayName: "Copy generated content for test A.G"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/output"
      contents: '**\*'
      targetFolder: $(Build.ArtifactStagingDirectory)/outpout
      cleanTargetFolder: true

  - task: CopyFiles@2
    displayName: "Copy deployment content for test A.G"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/deployment"
      contents: '**\*'
      targetFolder: $(Build.ArtifactStagingDirectory)/deployment
      cleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
